services:
  bot:
    build: python-app
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    - MISTRAL_TOKEN=${MISTRAL_TOKEN}
  redis:
    image: "redis:alpine"
  database:
    env_file: 
    - .env
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    build: db

    ports: 
    - "5432:5432"
    